import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Shoyeb',
      email: 'mdsoyeb@iut-dhaka.edu',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Abul',
      email: 'abul@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Red TShirt',
      slug: 'red-tshirt',
      category: 'tshirt',
      image: '/images/p2.jpg',
      price: 320,
      countInStock: 3,
      brand: 'ArtBoard',
      rating: 5,
      numReviews: 6,
      description: 'High Quality Tshirt with Red Illustration.',
    },
    {
      // _id: '2',
      name: 'IUT Turtle Neck (Green only)',
      slug: 'iut-turtle-neck',
      category: 'sweater',
      image: '/images/p4.jpg',
      price: 400,
      countInStock: 12,
      brand: 'ArtBoard',
      rating: 4,
      numReviews: 2,
      description: 'High Quality.',
    },
    {
      // _id: '3',
      name: 'Olive Oil',
      slug: 'olive-oil',
      category: 'food',
      image: '/images/p7.jpg',
      price: 560,
      countInStock: 10,
      brand: 'ArtBoard',
      rating: 5,
      numReviews: 1,
      description: 'High Quality.',
    },
    {
      // _id: '4',
      name: 'CSE Jersey 23',
      slug: 'cse-jersey-23',
      category: 'tshirt',
      image: '/images/p6.jpg',
      price: 500,
      countInStock: 0,
      brand: 'ArtBoard',
      rating: 5,
      numReviews: 20,
      description: 'High Quality.',
    },
    {
      // _id: '5',
      name: 'IUT Cap',
      slug: 'iut-cap',
      category: 'accessories',
      image: '/images/p10.jpg',
      price: 150,
      countInStock: 5,
      brand: 'ArtBoard',
      rating: 3,
      numReviews: 3,
      description: 'High Quality.',
    },
    {
      // _id: '6',
      name: 'IUT Jacket',
      slug: 'iut-jacket',
      category: 'jacket',
      image: '/images/p8.jpg',
      price: 850,
      countInStock: 5,
      brand: 'ArtBoard',
      rating: 4.5,
      numReviews: 3,
      description: 'High Quality.',
    },
    {
      // _id: '7',
      name: 'Brotherhood TShirt',
      slug: 'brotherhood-tShirt',
      category: 'tshirt',
      image: '/images/p5.jpg',
      price: 250,
      countInStock: 5,
      brand: 'ArtBoard',
      rating: 3,
      numReviews: 3,
      description: 'High Quality.',
    },
    {
      // _id: '8',
      name: 'Honey Pure',
      slug: 'honey-pure',
      category: 'food',
      image: '/images/p9.jpg',
      price: 350,
      countInStock: 5,
      brand: 'ArtBoard',
      rating: 3,
      numReviews: 3,
      description: 'High Quality.',
    },
  ],
};
export default data;
